---

- hosts: servidores_web
  become: yes
  remote_user: centos
  become_method: sudo
  vars:
    passwd_db: --> senha banco
    mysql_database: wpdatabase
    mysql_user: wpuser
    mysql_senha: adminadmin
    mysql_database2: magento
    mysql_user2: magentouser
    mysql_senha2: admin123
    api_user: ---> user do site do magento
    api_pass: ----> senha do site do magento
  tasks:
  - name: Update S.O
    yum:
      name: '*'
      state: latest
      update_cache: yes

  - name: Desabilitando o SELinux
    selinux:
      state: disabled

  - name: Baixando epel-release
    yum:
      name: epel-release
      state: latest

  - name: Instalando o nginx
    yum:
      name: nginx
      state: present
  - name: Start Nginx
    service:
      name: nginx
      state: started  
  - name: Habilitando Nginx
    service:
      name: nginx
      enabled: yes
  - name: Instalando remi repo.
    yum:
      name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
      state: present
  - name: Importando remi GPG key.
    rpm_key:
      key: http://rpms.remirepo.net/RPM-GPG-KEY-remi
      state: present
  - name: Enable php72 repo
    ini_file:
      dest: /etc/yum.repos.d/remi-php72.repo
      section: remi-php72
      option: enabled
      value: 1
  - name: Instalando php72
    yum:
      enablerepo: remi-php72
      name: php
      state: latest
      update_cache: yes
  - name: Instalando dependencias php72
    yum:
      enablerepo: remi-php72
      name: [ 'php','php-fpm','php-ctype', 'php-curl', 'php-dom', 'php-gd', 'php-mbstring', 'php-hash', 'php-openssl', 'php-simplexml', 'php-spl', 'php-libxml', 'php-xsl', 'php-json', 'php-iconv', 'php-mcrypt', 'php-bcmath', 'php-pdo_mysql', 'php-pecl-zip', 'php-mbstring', 'php-xml', 'php-xmlrpc', 'php-soap', 'php-intl', 'php-zip' ]
      state: latest
      update_cache: yes
  - name: Restart php-fpm
    service:
      name: php-fpm
      state: restarted
  - name: Habilitando PHP
    service:
      name: php-fpm
      enabled: yes
  - name: Adicionando repo MariaDB 10.5
    template:
      src: repo-mariadb.j2
      dest: /etc/yum.repos.d/MariaDB.repo

  - name: Update
    yum:
      name: '*'
      state: latest        
      update_cache: yes
  - name: Instalação MariaDB 10.5
    yum:
      name: mariadb-server
  - name: Start MariaDB
    service:
      name: mariadb
      state: started
  - name: Habilitando MariaDB
    service:
      name: mariadb
      enabled: yes  
  - name: Alterações no user www.sock
    replace:
      path: /etc/php-fpm.d/www.conf
      regexp: '(user = apache)'
      replace: 'user = nginx'
  - name: Alterações no group www.sock
    replace:
      path: /etc/php-fpm.d/www.conf
      regexp: '(group = apache)'
      replace: 'group = nginx'
  - name: Alterações no listen www.sock
    replace:
      path: /etc/php-fpm.d/www.conf
      regexp: '(listen = 127.0.0.1:9000)'
      replace: 'listen = /run/php-fpm/www.sock'
  - name: Alterações no listen.owner www.sock
    replace:
      path: /etc/php-fpm.d/www.conf
      regexp: '(;listen.owner = nobody)'
      replace: 'listen.owner = nginx'
  - name: Alterações no listen.group www.sock
    replace:
      path: /etc/php-fpm.d/www.conf
      regexp: '(;listen.group = nobody)'
      replace: 'listen.group = nginx'
  - name: Permissão para libphp
    file:
      path: /var/lib/php
      owner: root
      group: nginx
      mode: u+x
      recurse: yes    
  - name: Restart php
    service:
      name: php-fpm
      state: restarted
  - name: Start Nginx
    service:
      name: nginx
      state: restarted
  - name: Criando /var/www
    file:
      path: /var/www
      state: directory
      mode: '0755'
  - name: Criando /var/www/html
    file:
      path: /var/www/html
      mode: '0755'
      owner: nginx
      group: nginx
      state: directory
      recurse: yes
  - name: Criando /var/www/html/blog1.segundorobtech.tk
    file:
      path: /var/www/html/blog1.segundorobtech.tk
      mode: '0755'
      owner: nginx
      group: nginx
      state: directory
  - name: Criando /var/www/html/loja.segundorobtech.tk
    file:
      path: /var/www/html/loja.segundorobtech.tk
      mode: '0755'
      owner: nginx
      group: nginx
      state: directory
  - name: Criando /var/www/html/segundorobtech.tk
    file:
      path: /var/www/html/segundorobtech.tk
      mode: '0755'
      owner: nginx
      group: nginx
      state: directory
  - name: Download Wordpress
    get_url:
      url: https://wordpress.org/latest.tar.gz
      dest: /var/www/html/blog1.segundorobtech.tk
  - name: Descompactar wordpr7
    unarchive:
      src: /var/www/html/blog1.segundorobtech.tk/wordpress-5.7.tar.gz
      dest: /var/www/html/blog1.segundorobtech.tk
      remote_src: yes
  - name: Criando /var/www/html/blog1.segundorobtech.tk/logs
    file:
      path: /var/www/html/blog1.segundorobtech.tk/logs
      mode: '0755'
      owner: nginx
      group: nginx
      state: directory
  - name: Adicionando arquivo .conf do blog1
    template:
      src: wpconfig.conf.j2
      dest: "/etc/nginx/conf.d/blog1.segundorobtech.tk.conf"
  - name: Criando /var/www/html/blog1.segundorobtech.tk/logs
    file:
      path: /var/www/html/blog1.segundorobtech.tk/logs
      mode: '0755'
      owner: nginx
      group: nginx
      state: directory
  - name: Restart Nginx
    service:
      name: nginx
      state: restarted
  - name: Instalando Mysql Python
    yum:
      name: MySQL-python
  - name: Restart MariaDB
    service:
      service: mariadb
      state: restarted 
  - name: Password root MariaDB
    mysql_user:
      login_user: root
      login_password: cap1267
      name: root
      host_all: yes
      password: "{{ passwd_db }}"
      state: present
      login_unix_socket: /var/lib/mysql/mysql.sock
  - name: Removendo usuários anônimos
    mysql_user:
      name: ''
      host: localhost
      state: absent
      login_user: root
      login_password: "{{ passwd_db }}"
      login_unix_socket: /var/lib/mysql/mysql.sock
  - name: Criar database wordpress
    mysql_db:
      name: "{{ mysql_database }}"
      state: present
      login_user: root
      login_password: "{{ passwd_db }}"
      login_unix_socket: /var/lib/mysql/mysql.sock
  - name: Criando usuário do wordpress e acessos
    mysql_user:
      name: "{{ mysql_user }}"
      password: "{{ mysql_senha }}"
      priv: "{{ mysql_database }}.*:ALL"
      state: present
      login_user: root
      login_password: "{{ passwd_db }}"
      login_unix_socket: /var/lib/mysql/mysql.sock   
  - name: Adicoinando wp-config
    template:
      src: wp-config.j2
      dest: /var/www/html/blog1.segundorobtech.tk/wordpress/wp-config.php    
  - name: Restart Nginx
    service:
      name: nginx
      state: restarted
  - name: Restart PHP
    service:
      name: php-fpm
      state: restarted
  - name: Restart MariaDB
    service:
      name: mariadb
      state: restarted
  - name: Instalando JAVA
    yum:
      name: java-1.8.0-openjdk-devel
      state: present
  - name: Adicionando grupo tomcat
    group:
      name: tomcat
  - name: Adicionando usuário
    user:
      name: tomcat
      group: tomcat
      home: /opt/tomcat
      system: yes
  - name: Download tomcat
    get_url: 
      url: https://downloads.apache.org/tomcat/tomcat-9/v9.0.43/bin/apache-tomcat-9.0.43.tar.gz 
      dest: /opt/tomcat
  - name: Descompactar tomcat
    unarchive:
      src: /opt/tomcat/apache-tomcat-9.0.43.tar.gz
      dest: /opt/tomcat
      remote_src: yes
  - name: Permissão tomcat
    file:
      path: /opt/tomcat
      owner: tomcat
      group: tomcat
      mode: '0777'
      recurse: yes      
  - name: Adicionando arquivo systemd tomcat
    template:
      src: tomcat.service.j2
      dest: "/etc/systemd/system/tomcat.service"
  - name: Reload systemd
    systemd:
      daemon_reload: yes
  - name: Restart tomcat
    service:
      name: tomcat
      state: restarted
  - name: Alterações no user xml
    replace:
      path: /opt/tomcat/apache-tomcat-9.0.43/conf/tomcat-users.xml
      regexp: '(<user username="tomcat" password="<must-be-changed>" roles="tomcat"/>)'
      replace: '<user username="tomcat" password="admin58223" roles="tomcat"/>'
  - name: Excluindo arquivo tomcat contexto
    file:
      path: /opt/tomcat/apache-tomcat-9.0.43/webapps/manager/META-INF/context.xml
      state: absent
  - name: Adicionando arquivo de contexto
    template:
      src: tomcat.context.j2
      dest: "/opt/tomcat/apache-tomcat-9.0.43/webapps/manager/META-INF/context.xml"
  - name: Excluindo arquivo contexto 2
    file:
      path: /opt/tomcat/apache-tomcat-9.0.43/webapps/host-manager/META-INF/context.xml
      state: absent
  - name: Adicionando arquivo contexto 2
    template:
      src: tomcat.context2.j2
      dest: "/opt/tomcat/apache-tomcat-9.0.43/webapps/host-manager/META-INF/context.xml"
  - name: Restart tomcat
    service:
      name: tomcat
      state: restarted
  - name: Adicionando .conf do tomcat
    template:
      src: tomcat.conf.j2
      dest: /etc/nginx/conf.d/tom.segundorobtech.tk.conf
  - name: Restart nginx
    service:
      name: nginx
      state: restarted
  - name: Trocando .htl para /etc/yum.repos.d/remi-php72.repo
    template:
      src: estatico.j2
      dest: /etc/nginx/conf.d/segundorobtech.tk.conf
  - name: Adicionando arquivo de logs
    file:
      path: /var/www/html/segundorobtech.tk/logs
      state: directory
      mode: '0755'
  - name: Adicionando arquivo index
    template:
      src: indexestatico.j2
      dest: /var/www/html/segundorobtech.tk/index.php
  - name: Restart nginx
    service:
      name: nginx 
      state: restarted
  - name: Alterando arquivo php.ini
    replace:
      path: /etc/php.ini
      regexp:  '(zlib.output_compression = Off)'
      replace: 'zlib.output_compression = On'
  - name: Alterando arquivo php.ini
    replace:
      path: /etc/php.ini
      regexp: '(max_execution_time = 30)'
      replace: 'max_execution_time = 1800'
  - name: Alterando arquivos php.ini
    replace:
      path: /etc/php.ini
      regexp: '(memory_limit = 128M)'
      replace: 'memory_limit = 2G'
  - name: Alterando arquivos php.ini
    replace:
      path: /etc/php.ini
      regexp: '(;     session.save_path = "N;/path")'
      replace: 'session.save_path = "/var/lib/php/session"'
  - name: Alterando php.ini
    replace:
      path: /etc/php.ini
      regexp: '(;cgi.fix_pathinfo=1)'
      replace: 'cgi.fix_pathinfo=0'
  - name: Trocando dono e grupo do car lib php
    file:
      path: /var/lib/php
      owner: nginx
      group: nginx
      recurse: yes
  - name: Trocando dono e grupo do runphp
    file:
      path: /run/php-fpm
      owner: nginx
      group: nginx
      recurse: yes
  - name: Trocando dono e grupo do www.conf
    file:
      path: /etc/php-fpm.d
      owner: root
      group: root
      recurse: yes
  - name: Restart php-fpm
    service:
      name: php-fpm
      state: restarted
  - name: Criar database wordpress
    mysql_db:
      name: "{{ mysql_database2 }}"
      state: present
      login_user: root
      login_password: "{{ passwd_db }}"
      login_unix_socket: /var/lib/mysql/mysql.sock
  - name: Criando usuário do wordpress e acessos
    mysql_user:
      name: "{{ mysql_user2 }}"
      password: "{{ mysql_senha2 }}"
      priv: "{{ mysql_database2 }}.*:ALL"
      state: present
      login_user: root
      login_password: "{{ passwd_db }}"
      login_unix_socket: /var/lib/mysql/mysql.sock
  - name: Baixando php composer
    get_url:
      url: https://getcomposer.org/installer
      dest: /tmp/installer
  - name: Instalar o composer
    shell: cat /tmp/installer | php -- --install-dir=/usr/local/bin
    args:
      creates: /usr/local/bin/composer
  - name: Remoear composer
    shell: mv /usr/local/bin/composer.phar /usr/local/bin/composer
    args:
      creates: /usr/local/bin/composer
  - name: Composer executável
    file:
      path: /usr/local/bin/composer
      mode: a+x
      state: file
  - name: Criando link composer
    file:
      src: /usr/local/bin/composer
      dest: /usr/bin/composer
      state: link
  - name: Altera a versão composer 
    shell: composer self-update 1.9.0 

  - name: Setando chaves
    shell: composer config --global --global http-basic.repo.magento.com {{ api_user }} {{ api_pass }}
  - name: setando permisssão do loja-blog1
    file:
      path: /var/www/html/loja.segundorobtech.tk
      mode: '0755'
  - name: Projeto Composer
    get_url:
      url: https://github.com/magento/magento2/archive/2.3.zip
      dest: /var/www/html/loja.segundorobtech.tk
  - name: Instalando Unzip
    yum:
      name: unzip
      state: present
  - name: Descompactar magento2
    shell: >
      cd /var/www/html/loja.segundorobtech.tk	 &&
      ls -la &&
      unzip -o magento2-2.3.zip &&
      cd magento2-2.3/bin &&
      chmod u+x magento  


      #- name: Descompactar magento2
      #shell: cd /var/www/html/loja.segundorobtech.tk	 
      #ls -la  
      #unzip magento2-2.3.zip  
      #cd magento2-2.3.zip/bin  
      #chmod u+x magento

  - name: Restart nginx
    service:
      name: nginx
      state: restarted
  - name: Permissões blog1
    file:
      path: "/var/www/html/loja.segundorobtech.tk"
      owner: nginx
      group: nginx
      recurse: yes
  - name: executa composer install 
    shell: >
      cd /var/www/html/loja.segundorobtech.tk/magento2-2.3 && composer install     
  - name: Instalando Magento
    shell: >
      cd /var/www/html/loja.segundorobtech.tk/magento2-2.3/bin
      php -f ./bin/magento setup:install \
      --base-url=http://loja.segundorobtech.tk/ \
      --use-secure=0 \
      --db-host=localhost \
      --db-name=magento \
      --db-user=magentouser \
      --db-password=admin123 \
      --admin-firstname=roberto \
      --admin-lastname=silva \
      --admin-email=robertosilvaseg0@gmail.com \
      --admin-user=admin \
      --admin-password=admin123 \
      --language=en_US \
      --currency=USD \
      --timezone=America/Chicago \
      --use-rewrites=1 \
      --backend-frontname="admin" \
      --use-sample-data
    args:
      chdir: /var/www/html/loja.segundorobtech.tk
  - name: Recompilando magento
    shell: php bin/magento setup:di:compile
    args:
      chdir: /var/www/html/loja.segundorobtech.tk/magento2-2.3
  - name: Permissões magento
    shell: 
      cd /var/www/html/loja.segundorobtech.tk/magento2-2.3
      find var vendor pub/static pub/media app/etc -type f -exec chmod u+w {} \; && find var vendor pub/static pub/media app/etc -type d -exec chmod u+w {} \; && chmod u+x bin/magento
    args:
      chdir: /var/www/html/loja.segundorobtech.tk
  - name: Setando permissão
    file:
      path: "/var/www/html/loja.segundorobtech.tk"
      owner: nginx
      group: nginx
      recurse: yes
  - name: Arquivo conf da loja
    template:
      src: loja.conf.j2
      dest: /etc/nginx/conf.d/loja.segundorobtech.tk.conf
  - name: Restart php
    service:
      name: php-fpm
      state: restarted
  - name: Restart nginx
    service:
      name: nginx
      state: restarted
 - name: Instalando certbot
    yum:
      name: python2-certbot-nginx
      state: present
 - name: Aplicando SSL no blog1
   shell: certbot --nginx -d blog1.segundorobtech.tk	-d www.segundorobtech.tk	-d tom.segundorobtech.tk -d tom.segundorobtech.tk --email robertosilvaseg0@gmail.com --agree-tos


